# @link: <https://roadrunner.dev/docs/intro-config>

# rpc bus allows php application and external clients to talk to rr services.
rpc:
  # enable rpc server (enabled by default)
  enable: true

  # rpc connection DSN. Supported TCP and Unix sockets.
  listen: tcp://127.0.0.1:6001

# http service configuration.
http:
  # http host to listen.
  address: 0.0.0.0:80

#  ssl:
#    # custom https port (default 443)
#    port: 443
#
#    # force redirect to https connection
#    redirect: false
#
#    # ssl cert
#    cert: "/ssl-cert/self-signed.crt"
#
#    # ssl private key
#    key: "/ssl-cert/self-signed.key"
#
#  # HTTP service provides HTTP2 transport
#  http2:
#    # enable HTTP/2, only with TSL
#    enabled: true
#
#    # max transfer channels
#    maxConcurrentStreams: 128

  # max POST request size, including file uploads in MB.
  maxRequestSize: 1900

  # file upload configuration.
  uploads:
    # list of file extensions which are forbidden for uploading.
    forbid: [".php", ".exe", ".bat"]

  # cidr blocks which can set ip using X-Real-Ip or X-Forwarded-For
  trustedSubnets: ["10.0.0.0/8", "127.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "::1/128", "fc00::/7", "fe80::/10"]

  # http worker pool configuration.
  workers:
    # php worker command.
    #
    # Allowed arguments:
    # - `--(not-)force-https`
    # - `--(not-)reset-db-connections`
    # - `--(not-)reset-redis-connections`
    # - `--(not-)refresh-app`
    # - `--(not-)inject-stats-into-request`
    # - `--not-fix-symfony-file-validation`
    command: "php ./vendor/bin/rr-worker --refresh-app --reset-redis-connections"

    # connection method (pipes, tcp://:9000, unix://socket.unix). default "pipes"
    relay: "pipes"

    # worker pool configuration.
    pool:
      # number of workers to be serving.
      numWorkers: 4

      # maximum jobs per worker, 0 - unlimited.
      maxJobs: 20

      # for how long worker is allowed to be bootstrapped.
      allocateTimeout: 60

      # amount of time given to worker to gracefully destruct itself.
      destroyTimeout: 60

# Additional HTTP headers and CORS control.
headers:
  # Automatically add headers to every request passed to PHP.
  request:
  #  "Example-Request-Header": "Value"

  # Automatically add headers to every response.
  response:
    "X-Powered-By": "Microsoft-IIS/8.0"

# monitors rr server(s)
limit:
  # check worker state each second
  interval: 1

  # custom watch configuration for each service
  services:
    # monitor http workers
    http:
      # maximum allowed memory consumption per worker (soft)
      maxMemory: 256

      # maximum time to live for the worker (soft)
      TTL: 0

      # maximum allowed amount of time worker can spend in idle before being removed (for weak db connections, soft)
      idleTTL: 0

      # max_execution_time (brutal)
      execTTL: 60

# static file serving. remove this section to disable static file serving.
static:
  # serve http static files
  enable: true

  # root directory for static file (http would not serve .php and .htaccess files).
  dir: "public"

  # list of extensions for forbid for serving.
  forbid: [".php"]
